# Generated by Django 4.1.10 on 2023-07-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParallelSequenceLabelingProject",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.project",
                    ),
                ),
                ("allow_overlapping", models.BooleanField(default=False)),
                ("grapheme_mode", models.BooleanField(default=False)),
                ("use_relation", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projects.project",),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("DocumentClassification", "Document Classification"),
                    ("SequenceLabeling", "Sequence Labeling"),
                    ("ParallelSequenceLabeling", "Parallel Sequence Labeling"),
                    ("Seq2seq", "Seq2Seq"),
                    ("IntentDetectionAndSlotFilling", "Intent Detection And Slot Filling"),
                    ("Speech2text", "Speech2Text"),
                    ("ImageClassification", "Image Classification"),
                    ("BoundingBox", "Bounding Box"),
                    ("Segmentation", "Segmentation"),
                    ("ImageCaptioning", "Image Captioning"),
                ],
                max_length=30,
            ),
        ),
    ]
