# Generated by Django 4.1.10 on 2023-07-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_parallelsequencelabelingproject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parallelsequencelabelingproject",
            name="use_rating",
            field=models.BooleanField(default=False),
        ),
    ]
