# Generated by Django 4.1.10 on 2023-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0016_segmentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="parallel_text",
            field=models.IntegerField(null=True),
        ),
    ]
