# Generated by Django 4.1.10 on 2023-07-18 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0009_ratingtype_max_ratingtype_min_ratingtype_step_and_more"),
        ("examples", "0007_example_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labels", "0018_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("example", "user", "type")},
        ),
    ]
