# Generated by Django 4.1.10 on 2023-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0008_ratingtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingtype",
            name="max",
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name="ratingtype",
            name="min",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="ratingtype",
            name="step",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="ratingtype",
            name="ticks",
            field=models.TextField(blank=True),
        ),
    ]
